### ISSUE TITLE
Popravljen rvest

### ISSUE THREAD

**Issue by jaanos** [tilenklinc/APPR_projektna#3]
S posodobljeno različico knjižnice `rvest` bi moralo tabelo z Wikipedije pravilno uvoziti:
```R
library(devtools)
install_github("jaanos/rvest", ref="table-span-filling-v0.3.6.196")
```

**Comment by tilenklinc** [comment]
![slika](https://user-images.githubusercontent.com/64696152/101335001-e5595500-3878-11eb-8fd6-a80a8db3a103.png)

Ko poskusim pognati dano kodo dobim error code. (prilepljena slika težave).

**Comment by tilenklinc** [comment]
![slika](https://user-images.githubusercontent.com/64696152/101335683-d1622300-3879-11eb-88cc-d99322a6220a.png)
Po instalaciji Rtools-ov error še vedno ostaja.

**Comment by jaanos** [comment]
Izgleda, da ga moti, da je bila knjižnica `xml2` prevedena z drugo različico R-ja. Poskusi še s tem:
```R
install.packages("xml2", type="source")
```
Če po ponovnem poskusu dobiš podobno napako za drugo knjižnico, jo lahko poskusiš še enkrat namestiti na tak način.

**Comment by tilenklinc** [comment]
Popravek ustrezno deluje
