### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by katarinabrilej** [tilenklinc/APPR_projektna#4]
Knjižnice, ki jih potrebuješ za uvoz in jih imaš napisane na začetku datoteke `uvoz2.r` raje premakni v datoteko `libraries.r` v mapi `lib` (in tudi vse nadaljne knjižnice, ki jih boš potreboval za vizualizacijo, analizo, ...). Tako pred začetkom dela samo poženeš to datoteko.

Pri imenih stolpcev pa se raje izogibaj presledkov, npr. `Casovni_pas` namesto `Casovni pas`. Prav tako naj bodo imena stolpcev brez šumnikov.

**Comment by tilenklinc** [comment]
Če libraries izbrišem iz datoteke `uvoz2.r` ali mi bo ob začetnem pisanju in testiranju še vedno delovalo, ko kodo poženem v datoteki `uvoz2`?

**Comment by katarinabrilej** [comment]
Ja še vedno bo vse delovalo, samo najprej moraš pognati datoteko `libraries.r`. 

Načeloma imaš lahko zdaj še kakšno knjižnico v datoteki kjer uvažaš podatke, vendar se potem začnejo knjižnice, ki jih uporabljaš za vizualizacijo in analizo ponavljati in jih imaš potem večkrat napisane. Na koncu, ko boš pisal poročilo se te datoteke vse uvozijo in je potem hitreje, če imaš knjižnice samo v eni datoteki (libraries.r) in se samo enkrat uvozijo, kot pa da se uvažajo iz vsake datoteke  in torej kakšna večkrat.

**Comment by tilenklinc** [comment]
Popravljeno, hvala.
