### ISSUE TITLE
Oblike in tabela pri world graphu

### ISSUE THREAD

**Issue by tilenklinc** [tilenklinc/APPR_projektna#6]
Imam težavo pri oblikovanju world grapha.
Želim: na zemljevidu sveta bi z krogi označil borze, pri čemer bi posamična borza držala svojo barvo, velikost kroga pa bi bila odvisna od tržne kapitalizacije.
Problem:
* 1. Ob izrisu mi iz zemljevida izgine USA
* 2. V tabeli dobim tudi vrednost "NA" (funckija drop_na na stolpcu b&regions ne deluje) (zaenkrat je tabela skrita)
* 3. Ne najdem načina za zapis spreminjanja velikosti krogov v odvisnosti od tržne kapitalizacije.

**Comment by katarinabrilej** [comment]
Ko graf izrišem v Binderju mi ZDA ne izginejo iz zemljevida.

Glede na to, da podatki o borzah niso za vsako državo je smiselno, da dobiš v tabeli `b` tudi vrednosti `NA`.

Glede barve zemljevida je bolj intuitivno, če ni vsaka država s svojo barvo temveč je ena barva od svetle proti temni (torej od manjše proti večji tržni kapitalizaciji). 

Glede krogov na zemljevidu, ti so povezani s koordinatami in bi torej težko narisal vse borze, saj imaš v ZDA dve, ki sta v istem mestu, če bi torej borze povezal z mesti bi se bolj kot ne prekrivala. Ti pa da podobno informacijo o podatkih zgornja barvna skala, torej če gredo barve od svetle proti temni.

**Comment by jaanos** [comment]
Sem tudi sam poskusil, pa mi ZDA lepo prikaže na zemljevidu.

Sicer pa se mi `vizualizacija.r` ne požene - težava je očitno v `uvoz.r`:
https://github.com/tilenklinc/APPR_projektna/blob/e50ac1bf5578f309c4ffbdd175a815fee2b2696b/uvoz/uvoz2.r#L58-L61
Tako kot v `uvozi.AMD` bo treba odstraniti prirejanje spremenljivki (funkcija `getSymbols` očitno sama poskrbi za to, vrne pa le ime delnice kot niz).

Opozoril bi še na to, da v poročilu izrisuješ `graf2`, preden ga definiraš v `vizualizacija.r`, zato pride do napake. Pazi tudi na imena blokov kode (za `r` v glavi bloka kode, do prve vejice) - ta naj ne vsebujejo presledkov (pa tudi ne šumnikov in drugih posebnih znakov), saj potem grafi ne bodo delovali na Binderju.

Še to: vidim, da spremenljivke, ki jih dobiš s klici funkcij `candleChart` in `chartSeries`, pri klicanju tako izrišejo graf kot tudi izpišejo podatke - pri samem klicanju funkcije se slednje ne zgodi. Zato bo bolje, da te grafe v poročilu izrišeš tako, da kličeš ustrezno funkcijo (tj., ne shranjuješ v spremenljivko v `vizualizacija.r`).

**Comment by tilenklinc** [comment]
Popravil vse zapisano, težavo imam še z zapisom funkcije in prikazu krogov na mestu borz. Barvo sem določil po velikosti borz, težava nastane, da legenda kaže vrednosti med 0-1000, kar ne ustreza vrednostim, ki jih imam zapisane v tabeli. Sklepam, da nisem pravilno nastavil iz kje naj pobira vrednosti. Iz istega razloga mi tudi graf neustrezno pobarva.

**Comment by katarinabrilej** [comment]
Problem je v tem, da so podatki v tabeli `a` oz. že prej v tabeli `kapitalizacija` napačno prebrani. Recimo za NYSE je vrednost 22.923 namesto 22923. To popraviš tako, da v funkciji `uvozi.kapitalizacijo` naslednji dve vrstici 
```
  tabela$Market_cap <- as.numeric(gsub(",",".",tabela$Market_cap))
  tabela$Monthly_volume <- as.numeric(gsub(",",".",tabela$Monthly_volume))
```
zamenjaš za
```
  tabela$Market_cap <- as.numeric(gsub(",","",tabela$Market_cap))
  tabela$Monthly_volume <- as.numeric(gsub(",","",tabela$Monthly_volume))
```

Torej vejic ne zamenjaš v pike, ker to niso decimalne vejice.

**Comment by tilenklinc** [comment]
Dobro opažanje, hvala.
