### ISSUE TITLE
Dodajanje grafa z logaritemsko skalo

### ISSUE THREAD

**Issue by tilenklinc** [tilenklinc/APPR_projektna#7]
Želel bi si dodati graf na katerem bi bile predstavjlene vse pridobljene delnice. Težava je pri tem, da če samo izrišem graf, zaradi večjih razlik v ceni delnic izgubim nekatere "detajle". Želel bi si da bi se vse cene začele pri 1. Tako sem razmišljal da bi z mutate ustvaril nov stolpec procentualnh vrednosti, pri čemer bi vse pripadajoče delnice Tipa OPEN delil z vrednostjo na prvi dan. Nato pa bi združil in vse dodal, vendar mi na ta način ni uspelo narediti, zato prosim za nasvet/pomoč s kodo.

`procentAMD <- zdruzena2 %>% filter(Ime == "AMD")
procentAMD <- zdruzena2 %>% mutate(Procent = Vrednost / procentAMD$Vrednost[1])`
Poskusil sem tako, vendar brez uspeha.

...
`
graf1 <- ggplot(zdruzena %>% filter(Tip == "Open",
                           Ime %in% c("AAPL","NVDA","AMZN","MSFT","AMD", "INTC","ADBE", "SNE")),
       aes(x=Datum, y=Vrednost, color=Ime)) + geom_line() + ggtitle("Cena delnic skozi čas") + 
  ylab("Cena na delnico [$]") + xlab("Leto")
`
Ta koda je le za graf brez procentualnih vrednosti.

**Comment by katarinabrilej** [comment]
Logaritemsko skalo lahko dodaš tako, da na koncu podaš `scale_y_continuous(trans = 'log10')` ali pa `scale_y_continuous(trans = 'log2')`. Torej
```
graf1 <- ggplot(zdruzena %>% filter(Tip == "Open",
                           Ime %in% c("AAPL","NVDA","AMZN","MSFT","AMD", "INTC","ADBE", "SNE")),
       aes(x=Datum, y=Vrednost, color=Ime)) + geom_line() + ggtitle("Cena delnic skozi čas") + 
  ylab("Cena na delnico [$]") + xlab("Leto") + scale_y_continuous(trans = 'log10')
```

**Comment by tilenklinc** [comment]
Najlepša hvala, ta rešitev mi ustrezno deluje.
Samo še informativno ... kako bi lahko podatke oblikoval tako, da bi se vsi začeli pri y = 1 nato pa se skozi čas spreminjali glede na spremembo cen delnic?

**Comment by jaanos** [comment]
Če bi želel podatke oblikovati na tak način, bi lahko najprej pridobil začetne vrednosti, nato pa podatke delil z ustreznimi začetnimi vrednostmi, da dobiš normirane podatke, npr.
```R
zacetne <- zdruzena %>% group_by(Ime, Tip) %>%
  slice_min(Datum, n=1, with_ties=FALSE) %>%
  transmute(Ime, Tip, ZacetnaVrednost=Vrednost)
normirana <- inner_join(zdruzena, zacetne) %>%
  mutate(NormiranaVrednost=Vrednost/ZacetnaVrednost) %>%
  select(-ZacetnaVrednost)
```

**Comment by tilenklinc** [comment]
Hvala, z navedeno kodo sem dopolnil datoteko vizualizacija.r, sedaj mi deluje.
